// test/check-versions.test.ts — scripts/check-versions.sh (Phase E, E9): the four version carriers and
// the versioned size-budget row paths.
//
// The script resolves the carriers from its own location (`<script>/..`), so each case copies the REAL
// script into a fixture tree that has the repo's layout and nothing else. The fixture carriers are
// shaped like the real ones (a Cargo.toml with dependency tables carrying their own `version`, a
// Cargo.lock with neighbouring packages), so a parser that grabbed the first `version` it saw fails.
import "./fixtures/isolate-state";
import { test, expect, describe } from "bun:test";
import { copyFileSync, mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { removeAtRunEnd } from "./fixtures/temp-dirs";

const SCRIPT = join(resolve(import.meta.dir, ".."), "scripts", "check-versions.sh");

interface Versions { root: string; gui: string; toml: string; lock: string; dmgPath: string | null; appPath: string | null }
const V = "0.2.0";
const ALL: Versions = {
  root: V, gui: V, toml: V, lock: V,
  dmgPath: `src-tauri/target/release/bundle/dmg/Daily Briefing_${V}_aarch64.dmg`,
  appPath: "src-tauri/target/release/bundle/macos/Daily Briefing.app",
};

function fixture(v: Versions, opts: { lockEntries?: number } = {}): string {
  const root = removeAtRunEnd(mkdtempSync(join(tmpdir(), "dba-versions-")));
  mkdirSync(join(root, "scripts"));
  mkdirSync(join(root, "gui", "src-tauri"), { recursive: true });
  copyFileSync(SCRIPT, join(root, "scripts", "check-versions.sh"));
  writeFileSync(join(root, "package.json"), JSON.stringify({ name: "daily-briefing", version: v.root, devDependencies: { x: "1.0.0" } }, null, 2));
  writeFileSync(join(root, "gui", "package.json"), JSON.stringify({ name: "daily-briefing-gui", version: v.gui }, null, 2));
  // A dependency table with its own `version` sits ABOVE [package] (TOML allows any table order), so a
  // parser that is not scoped to [package] reads 9.9.9 and fails every case.
  writeFileSync(join(root, "gui", "src-tauri", "Cargo.toml"), [
    "[dependencies.early]",
    'version = "9.9.9"',
    "",
    "[package]",
    'name = "daily-briefing-gui"',
    `version = "${v.toml}"`,
    'rust-version = "1.98.1"',
    "",
    "[build-dependencies]",
    'tauri-build = { version = "=2.6.3", features = [] }',
    "",
    "[dependencies.serde]",
    'version = "9.9.9"',
    "",
  ].join("\n"));
  const gui = `[[package]]\nname = "daily-briefing-gui"\nversion = "${v.lock}"\ndependencies = [\n "libc",\n]\n`;
  writeFileSync(join(root, "gui", "src-tauri", "Cargo.lock"), [
    "# This file is automatically @generated by Cargo.",
    "version = 4",
    "",
    '[[package]]\nname = "cfg-if"\nversion = "1.0.0"\n',
    ...Array.from({ length: opts.lockEntries ?? 1 }, () => gui),
    '[[package]]\nname = "daily-briefing-gui-helper"\nversion = "7.7.7"\n',
  ].join("\n"));
  const row = (path: string | null) => ({ budgetBytes: null, measuredBytes: path ? 1 : null, measuredAt: null, path });
  writeFileSync(join(root, "gui", "size-budget.json"), JSON.stringify({
    sidecar: { measuredBytes: 1, path: "src-tauri/binaries/daily-briefing-aarch64-apple-darwin" },
    artifacts: {
      "app-aarch64-apple-darwin": row(v.appPath),
      "dmg-aarch64-apple-darwin": row(v.dmgPath),
      "dmg-x86_64-apple-darwin": row(null),
    },
  }, null, 2));
  return root;
}

function check(root: string, version = V) {
  const r = Bun.spawnSync(["bash", join(root, "scripts", "check-versions.sh"), version], { env: { ...process.env }, stdout: "pipe", stderr: "pipe" });
  return { code: r.exitCode, out: r.stdout.toString(), err: r.stderr.toString() };
}

describe("check-versions.sh", () => {
  test("all four carriers equal and the versioned row current -> 0", () => {
    const r = check(fixture(ALL));
    expect(`${r.code}\n${r.err}`).toBe("0\n");
    expect(r.out).toMatch(/PASS/);
  });

  const carriers: [keyof Versions, string][] = [
    ["root", "package.json"],
    ["gui", "gui/package.json"],
    ["toml", "gui/src-tauri/Cargo.toml"],
    ["lock", "gui/src-tauri/Cargo.lock"],
  ];
  for (const [key, file] of carriers) {
    test(`${file} one patch behind -> 1, naming that file and only that file`, () => {
      const r = check(fixture({ ...ALL, [key]: "0.1.9" }));
      expect(r.code).toBe(1);
      const fails = r.err.split("\n").filter((l) => l.startsWith("FAIL:"));
      expect(fails).toHaveLength(1);
      expect(fails[0]).toStartWith(`FAIL: ${file}`);
      expect(fails[0]).toContain("0.1.9 != 0.2.0");
      expect(r.err).toMatch(/bundle names take their version from gui\/package\.json/);
    });
  }

  test("a stale versioned size-row path -> 1, naming the row", () => {
    const r = check(fixture({ ...ALL, dmgPath: "src-tauri/target/release/bundle/dmg/Daily Briefing_0.1.1_aarch64.dmg" }));
    expect(r.code).toBe(1);
    expect(r.err).toMatch(/FAIL: gui\/size-budget\.json: row dmg-aarch64-apple-darwin path .* does not carry _0\.2\.0_/);
  });

  test("version-free paths (the .app row, the sidecar) and null paths are ignored", () => {
    const r = check(fixture({ ...ALL, appPath: "src-tauri/target/release/bundle/macos/Something Else.app" }));
    expect(`${r.code}\n${r.err}`).toBe("0\n");
    expect(r.out).toMatch(/app-aarch64-apple-darwin \(version-free path, exempt\)/);
    expect(r.out).toMatch(/sidecar \(version-free path, exempt\)/);
  });

  test("Cargo.lock with no daily-briefing-gui entry, or two -> 1", () => {
    for (const n of [0, 2]) {
      const r = check(fixture(ALL, { lockEntries: n }));
      expect(r.code).toBe(1);
      expect(r.err).toMatch(new RegExp(`expected exactly one daily-briefing-gui package entry \\(${n} found\\)`));
    }
  });

  test("a version argument that is not plain semver, or none -> 1", () => {
    const root = fixture(ALL);
    for (const v of ["v0.2.0", "0.2.0-rc.1", "0.2", ""]) expect(check(root, v).code).toBe(1);
    const r = Bun.spawnSync(["bash", join(root, "scripts", "check-versions.sh")], { env: { ...process.env }, stdout: "pipe", stderr: "pipe" });
    expect(r.exitCode).toBe(1);
  });

  test("every mismatch is reported, not just the first", () => {
    const r = check(fixture({ ...ALL, root: "0.1.9", lock: "0.1.8", dmgPath: "x/Daily Briefing_0.1.1_aarch64.dmg" }));
    expect(r.code).toBe(1);
    expect(r.err.split("\n").filter((l) => l.startsWith("FAIL:"))).toHaveLength(3);
  });
});
