//! Build-time ACL generation.
//!
//! ⚠ AN APP ACL MANIFEST IS WHAT MAKES THE CAPABILITY MEAN ANYTHING, and that is not obvious.
//! Tauri 2 ACL-checks an application's own commands **only when the app declared an ACL manifest**
//! — `webview/mod.rs:1823-1826`: `if (plugin_command.is_some() || has_app_acl_manifest || !is_local)
//! && request.cmd != FETCH_CHANNEL_DATA_COMMAND && invoke.acl.is_none() { reject }` (the
//! `FETCH_CHANNEL_DATA_COMMAND` exemption is Tauri's own channel plumbing, not an app command).
//! Without a manifest, `has_app_acl_manifest` is false, every `#[tauri::command]` in this crate is
//! reachable from the local webview whatever `capabilities/default.json` says, and the capability
//! would be documentation.
//!
//! ⚠ THE MANIFEST HAS TWO SOURCES, AND EITHER ONE ALONE KEEPS THE GATE UP — measured on a
//! disposable copy, all four combinations:
//!
//!   * **`.commands(…)` below.** `tauri-build` autogenerates an `allow-<command>` /
//!     `deny-<command>` permission pair per name into `permissions/autogenerated/` (`tauri-build`
//!     `acl.rs:274-289`; the `_`→`-` slugify is `tauri-utils` `acl/build.rs:290`).
//!   * **The committed `permissions/` directory.** With the call removed, `app_manifest_permissions`
//!     falls through to its default `permissions/**/*` glob (`tauri-build` `acl.rs:300-328`) and
//!     finds the same files. `has_app_manifest` is `default_permission.is_some() ||
//!     !permission_sets.is_empty() || !permissions.is_empty()` (`acl.rs:408-410`), so either source
//!     makes it true.
//!
//!   | `.commands(…)` | `permissions/` | result |
//!   | --- | --- | --- |
//!   | kept | deleted | regenerated at build; capability tests green |
//!   | removed | kept | glob finds the committed files; capability tests green |
//!   | removed | removed (grants kept) | `failed to run custom build command` — the capability references permissions no manifest defines |
//!   | removed | removed (grants removed too) | builds; the engine commands are UNGATED; the structural tests go red |
//!
//! So the gate is pinned by `commands(…)` ∨ the committed directory, and only removing both
//! (and then editing the capability to match) reaches the ungated state. The directory is
//! committed because it is a REGENERABLE, TRACKED SNAPSHOT that makes the manifest reviewable in a
//! diff — not because it is the sole gate. `tauri-utils` writes it with `write_if_changed` and
//! never deletes a file (`acl/build.rs:307-309`), so a RENAMED command leaves `<old>.toml` behind
//! defining a permission nothing grants; `tests/capability.rs`'s
//! `autogenerated_permissions_match_the_command_set` is what catches that, and
//! `the_capability_grants_exactly_the_app_commands` pins this list, the capability's grants,
//! `commands::all_commands()` and `lib.rs`'s `generate_handler!` against each other.
//!
//! Everything else `tauri_build::build()` did still happens: `tauri.conf.json` and
//! `capabilities/*.json` are parsed and the RESOLVED ACL is baked into the binary, so a malformed
//! capability is a compile error here rather than a runtime surprise.

fn main() {
    let attributes = tauri_build::Attributes::new()
        .app_manifest(tauri_build::AppManifest::new().commands(daily_briefing_gui_commands()));
    if let Err(error) = tauri_build::try_build(attributes) {
        panic!("failed to run tauri-build: {error:#}");
    }
}

/// The command list, duplicated from `engine::COMMANDS` + `shell::COMMANDS` +
/// `briefing_files::COMMANDS` + `config_save::COMMANDS` (in that order — see `commands.rs`'s
/// `all_commands`) because a build script cannot import its own crate.
/// `tests/capability.rs` asserts the two agree, so the duplication cannot drift silently — which is
/// the only reason it is tolerable.
fn daily_briefing_gui_commands() -> &'static [&'static str] {
    &[
        "engine_status",
        "engine_doctor",
        "engine_run",
        "engine_run_to_file",
        "engine_config_validate",
        "engine_schedule_install",
        "engine_schedule_uninstall",
        "engine_schedule_status",
        // B6 (T20): `schedule verify --json`. MUTATING — the kick starts the live launchd job, so
        // this grant is "may make the scheduler run the engine now", not "may check something".
        "engine_schedule_verify",
        // Phase E (E12): `update --check --json`, the Settings screen's "Check now". NOT mutating —
        // its one write is the engine's own update-check record — and it takes no operand.
        "engine_update_check",
        // T11's shell commands. Not `engine_*`: they spawn nothing — they read the app's own
        // window and state. The capability names them one at a time all the same, because the
        // grant is per command name and "may raise the window" is not "may quit the app".
        "state_snapshot",
        "open_today",
        "app_quit",
        // B5 (T12/T13): READ-only access to the two engine files a briefing lives in. Each runs
        // `status --json` and joins onto the engine's own paths; the archive command takes a date,
        // never a path.
        "read_latest_briefing",
        "read_archived_briefing",
        // B5 (T15): the app's one config-write path. Settings reads and saves through the first
        // two; the Quit dialog's `notify: "auto"` offer is the third, over the same pipeline.
        "config_read",
        "config_save",
        "config_offer_notify_auto",
        // B8 (T16): the FIRST-config path — the wizard's one write. Exclusive create (nothing
        // that already holds the name is ever replaced), engine-validated, no key and no
        // transcripts block accepted. Closes §10e's open design point (deviation 42).
        "config_create",
        // B6 (T17): the folder-access flow. Four grants rather than one, because "may read one
        // protected folder from this process" (the macOS prompt trigger), "may reveal the managed
        // engine copy in Finder" and "may open a System Settings pane" are three different powers
        // and the first is the only one that can raise a system dialog. None takes a path or a URL.
        "access_snapshot",
        "access_probe",
        "access_reveal_engine",
        "access_open_settings",
        // B7 (T18): the app's notification opt-in. `notify_status` reads the record, the ENGINE's
        // resolved notify value and the suppression log; `notify_set_enabled` is the explained
        // ask's answer (a user gesture in Settings/Schedule — and B8's wizard step). Neither takes
        // a path; nothing here can post a notification.
        "notify_status",
        "notify_set_enabled",
        // B8 (dev 63): the CLI-shim Settings action. Three grants because "say what is there",
        // "write a symlink in /usr/local/bin" and "remove that symlink" are three different
        // powers; none takes an operand — the target is re-read from `schedule status --json`
        // and a foreign file at the name is refused, never replaced or removed.
        "cli_shim_status",
        "cli_shim_install",
        "cli_shim_remove",
        // B25 (T25): the uninstall action. Two grants because "say what would be removed" and
        // "remove it" are two different powers; the execute's one operand is the EXPLICIT
        // consent boolean for the engine-state leg, whose file list is pinned against
        // scripts/uninstall.sh at test time and whose target dir is re-read from the engine —
        // the webview can name no path.
        "uninstall_preview",
        "uninstall_execute",
        // Phase E M5b (T19 reworked): the login item. `autostart_set_enabled` takes one boolean —
        // ON is the plugin's `enable()` plus the macOS branding, OFF its `disable()` — and replaces
        // the plugin's own enable/disable grants, so no unbranded ON is reachable from the webview;
        // `autostart_wizard_default` READS the record and the real state for the wizard's last
        // step. Neither takes a path; the plist's content is the plugin's fixed derivation plus
        // the fixed bundle identifier.
        "autostart_set_enabled",
        "autostart_wizard_default",
    ]
}
