/**
 * B6 — T17's folder-access flow and T20's verification / removal rules, rendered by the real Svelte
 * compiler and asserted as markup, plus the pure modules behind them.
 *
 * ⚠ THE GOLDEN FOR THE ADVICE TEXT IS THE ENGINE ITSELF. `warnFor` is imported READ-ONLY from
 * `src/protectedPath.ts` — the same shared-fixture discipline `briefing.check.ts` uses for
 * `renderBriefing` — because appendix T17 requires the engine's advice *"displayed unmodified"* and
 * a checked-in copy of that sentence would drift the moment the engine reworded it. The fixture is
 * generated by CALLING the engine function; nothing here re-spells it.
 *
 * ⚠ NOTHING HERE TOUCHES A REAL PROTECTED FOLDER, opens anything, or reaches the engine: SSR
 * renders markup and runs no click handler (`docs/gui-seam.md` §10f), and every rule under test is
 * a pure function over data this file constructs.
 */
import { describe, expect, test } from "bun:test";
import { render } from "svelte/server";

// READ-ONLY import of the engine's own advice writer. `protectedPath.ts` imports only `node:os` and
// `node:path` and has no Bun-only API, so it loads here directly.
import { warnFor } from "../../src/protectedPath";
import ForeignOwnerDialog from "../src/lib/ForeignOwnerDialog.svelte";
import ScheduleAccess from "../src/lib/ScheduleAccess.svelte";
import ScheduleUninstall from "../src/lib/ScheduleUninstall.svelte";
import ScheduleVerify from "../src/lib/ScheduleVerify.svelte";
import { describeAccess, launchActions, type AccessSnapshot, type ProbeResult } from "../src/lib/access";
import {
  afterKeep,
  afterUninstall,
  foreignOwnerLead,
  uninstallConfirmation,
  uninstallLine,
} from "../src/lib/uninstall-flow";
import {
  afterKick,
  afterKickRefusal,
  afterVerify,
  armLoop,
  beginKick,
  isNewEvidence,
  MAX_VERIFY_ATTEMPTS,
  onEvidence,
  verifyEnvelope,
  type VerifyEvidence,
} from "../src/lib/verify-flow";
import type { EngineOutcome } from "../src/lib/engine";
import type { ScheduleState } from "../src/lib/state";

const HOSTILE = '<img src=x onerror="alert(1)">';

function html(component: unknown, props: Record<string, unknown>): string {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return render(component as any, { props })
    .body.replace(/<!--[\s\S]*?-->/g, "")
    .replace(/\s+/g, " ");
}

function buttons(body: string): string[] {
  return [...body.matchAll(/<button[^>]*>([\s\S]*?)<\/button>/g)].map((m) => (m[1] ?? "").trim());
}

/**
 * The five entities Svelte's escaper emits, turned back into the characters they stand for.
 *
 * ⚠ THE ESCAPING IS THE PROOF, NOT AN OBSTACLE. The engine's advice contains `&` (in "Privacy &
 * Security" and "Files & Folders"), which reaches the markup as `&amp;` precisely because the
 * string is drawn as a TEXT NODE rather than as markup. Comparing the decoded text is what
 * "verbatim" means here; comparing the raw markup would assert the opposite of what this app wants.
 */
function decode(text: string): string {
  return text
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&amp;/g, "&");
}

function snapshot(extra: Partial<AccessSnapshot> = {}): AccessSnapshot {
  return {
    supported: true,
    roots: [],
    doctorVerdict: "ready",
    reposTimedOut: false,
    grantObserved: false,
    probeAdvice: "none",
    probeRoot: null,
    versionChange: { kind: "same" },
    appVersion: "0.1.1",
    managedEnginePath: null,
    configMissing: false,
    notes: [],
    ...extra,
  };
}

function outcome(extra: Partial<EngineOutcome> = {}): EngineOutcome {
  return {
    operation: "schedule-verify",
    outcome: { kind: "delivered" },
    exitCode: 0,
    payload: null,
    stdout: "",
    stderr: "",
    ...extra,
  };
}

function scheduleState(extra: Partial<ScheduleState> = {}): ScheduleState {
  return {
    phase: { phase: "waiting-for-wake" },
    statusLine: "Waiting",
    floor: "07:20",
    floorWarning: null,
    firstWake: "first wake",
    ticksToday: 3,
    ticksExpectedSinceFloor: 3,
    lastTick: null,
    owner: "app",
    invoker: "app",
    unitPath: "/Users/x/Library/LaunchAgents/local.daily-briefing.plist",
    registered: true,
    recordPresent: true,
    unitPresent: true,
    engineVersion: "0.1.1",
    installedEngineVersion: "0.1.1",
    engineUpdateAvailable: false,
    intervalSec: 600,
    experimental: false,
    lingerState: "not-applicable",
    recordFilePresent: true,
    registeredReason: null,
    removeSteps: "Run these in a terminal (bash or zsh) inside your desktop session.",
    ...extra,
  };
}

/* ── T17: the panel ───────────────────────────────────────────────────────────────────────────── */

describe("ScheduleAccess.svelte", () => {
  test("off macOS the whole step is absent", () => {
    const body = html(ScheduleAccess, { snapshot: snapshot({ supported: false }) });
    expect(body.trim()).toBe("");
    // And before the first snapshot there is nothing either — no half-rendered flow.
    expect(html(ScheduleAccess, { snapshot: null }).trim()).toBe("");
  });

  test("with nothing protected in scope it says so and offers no grant step", () => {
    const body = html(ScheduleAccess, { snapshot: snapshot() });
    expect(body).toContain("None of the folders your briefing reads is one macOS protects");
    expect(body).not.toContain("This app");
    expect(body).not.toContain("The background copy of the engine");
    // The panel is still available — plan R1 makes it always reachable — so Re-check is there.
    expect(buttons(body)).toEqual(["Re-check"]);
  });

  test("v0.2.1 §3.4: with no config yet the engine check waits for setup and no read failure is shown", () => {
    // What Rust answers while the wizard is open: doctor says `blocked` (there is no config to be
    // valid) and `config.exists: false`, so `configMissing` is set and the read note is not added.
    const body = html(ScheduleAccess, {
      snapshot: snapshot({ doctorVerdict: "blocked", configMissing: true, notes: [] }),
    });
    expect(body).toContain("Engine check: available once setup is finished.");
    expect(body).not.toContain("Engine check: blocked");
    expect(body).not.toContain("could not be read");
    expect(body).not.toContain("config.json");
    // Even a verdict-less envelope says the same: the flag alone decides the line.
    const noVerdict = html(ScheduleAccess, {
      snapshot: snapshot({ doctorVerdict: null, configMissing: true }),
    });
    expect(noVerdict).toContain("Engine check: available once setup is finished.");
  });

  test("v0.2.1 §3.4: with a config present, a blocked check and a read note keep today's lines", () => {
    const note =
      "The config could not be read, so only the folders the engine already reported are listed here: /Users/x/.daily-briefing/config.json does not exist";
    const body = html(ScheduleAccess, {
      snapshot: snapshot({ doctorVerdict: "blocked", configMissing: false, notes: [note] }),
    });
    expect(body).toContain("Engine check: blocked.");
    expect(body).toContain(note);
    expect(body).not.toContain("available once setup is finished");
    // And a ready config is unchanged too.
    const ready = html(ScheduleAccess, { snapshot: snapshot() });
    expect(ready).toContain("Engine check: ready.");
    expect(ready).not.toContain("available once setup is finished");
  });

  test("the engine's advice is rendered VERBATIM, generated by calling warnFor", () => {
    // The fixture IS the engine's output for this issue.
    const advice = warnFor({
      path: "/Users/x/Documents/proj",
      kind: "tcc-denied",
      protectedRoot: "/Users/x/Documents",
    });
    expect(advice).toContain("TCC-blocked");
    const body = html(ScheduleAccess, {
      snapshot: snapshot({
        roots: [
          {
            key: "documents",
            path: "/Users/x/Documents",
            denied: [{ path: "/Users/x/Documents/proj", advice }],
            because: ["/Users/x/Documents/proj"],
          },
        ],
      }),
    });
    // ⚠ EQUALITY, NOT CONTAINMENT, over the advice block's own text. A `toContain` would pass for a
    // panel that appended its own sentence to the engine's — which is exactly what "displayed
    // unmodified" forbids. Whitespace is collapsed on both sides (`html()` does it to the markup
    // and the engine writes the advice as one line, so this changes nothing about it).
    const rendered = /<pre class="advice[^"]*">([\s\S]*?)<\/pre>/.exec(body);
    expect(rendered).not.toBeNull();
    expect(decode((rendered?.[1] ?? "").trim())).toBe(advice.replace(/\s+/g, " "));
    // Both principals are guided — SPK-1(b)'s inheritance leg is UNRUN, so neither is assumed.
    expect(body).toContain("1. This app");
    expect(body).toContain("2. The background copy of the engine");
  });

  test("both System Settings panes are offered, with what each grants, and the manual fallback", () => {
    const body = html(ScheduleAccess, {
      snapshot: snapshot({
        managedEnginePath: "/Users/x/Library/Application Support/daily-briefing/daily-briefing",
        roots: [
          { key: "desktop", path: "/Users/x/Desktop", denied: [], because: ["/Users/x/Desktop"] },
        ],
      }),
    });
    const labels = buttons(body);
    expect(labels).toContain("Open Files &amp; Folders settings");
    expect(labels).toContain("Open Full Disk Access settings");
    expect(labels).toContain("Open Privacy &amp; Security");
    expect(labels).toContain("Show it in Finder");
    // Honest about what each one grants.
    expect(body).toContain("one protected folder at a time");
    expect(body).toContain("everything on the Mac");
    // The deep links are UNVERIFIED on macOS 26, so the manual path is always shown — not revealed
    // on failure, because a link that lands on the wrong pane reports no error.
    expect(body).toContain("If the button opens the wrong page");
    expect(body).toContain("x-apple.systempreferences:com.apple.preference.security?Privacy_Files");
    expect(body).toContain(
      "x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles",
    );
    // And the managed copy is named, because that is the file the user has to drag in.
    expect(body).toContain("/Users/x/Library/Application Support/daily-briefing/daily-briefing");
  });

  test("v0.2.1 §3.3: the background copy's step names no clock time — it is the MORNING briefing", () => {
    // The panel is shared by wizard step 4 and Schedule › Folder access; it cannot know the configured
    // time, and "Your 7:20 briefing" was wrong for anyone who set another.
    const body = html(ScheduleAccess, {
      snapshot: snapshot({
        roots: [
          { key: "desktop", path: "/Users/x/Desktop", denied: [], because: ["/Users/x/Desktop"] },
        ],
      }),
    });
    expect(body).toContain("2. The background copy of the engine");
    expect(body).toContain(
      "Your morning briefing is not generated by this app. It is generated by a copy of the engine that the background scheduler installed",
    );
    expect(body).not.toContain("7:20");
  });

  test("with no managed copy the reveal is disabled and says why", () => {
    const body = html(ScheduleAccess, {
      snapshot: snapshot({
        roots: [
          { key: "desktop", path: "/Users/x/Desktop", denied: [], because: ["/Users/x/Desktop"] },
        ],
      }),
    });
    expect(body).toContain("No background scheduler is installed yet");
    expect(body).toMatch(/<button[^>]*disabled[^>]*>\s*Show it in Finder/);
  });

  test("a new app version says macOS asks again after an update", () => {
    const body = html(ScheduleAccess, {
      snapshot: snapshot({
        versionChange: { kind: "changed", from: "0.1.0" },
        roots: [
          { key: "desktop", path: "/Users/x/Desktop", denied: [], because: ["/Users/x/Desktop"] },
        ],
      }),
    });
    expect(body).toContain("macOS asks for folder access again after an update");
    // …and not when nothing protected is in scope: a warning with no action.
    const none = html(ScheduleAccess, {
      snapshot: snapshot({ versionChange: { kind: "changed", from: "0.1.0" } }),
    });
    expect(none).not.toContain("macOS asks for folder access again");
  });

  test("every engine-supplied string stays literal text", () => {
    const body = html(ScheduleAccess, {
      snapshot: snapshot({
        managedEnginePath: HOSTILE,
        notes: [HOSTILE],
        roots: [
          {
            key: "documents",
            path: HOSTILE,
            denied: [{ path: HOSTILE, advice: HOSTILE }],
            because: [HOSTILE],
          },
        ],
      }),
      launchProbe: {
        root: "documents",
        path: HOSTILE,
        access: { kind: "denied", errno: 1 },
        recorded: false,
        note: HOSTILE,
      } satisfies ProbeResult,
    });
    expect(body).not.toContain("<img");
    expect(body).toContain("&lt;img");
  });

  test("the launch check's result is shown until the panel runs one of its own", () => {
    const body = html(ScheduleAccess, {
      snapshot: snapshot({
        roots: [
          {
            key: "documents",
            path: "/Users/x/Documents",
            denied: [],
            because: ["/Users/x/Documents"],
          },
        ],
      }),
      launchProbe: {
        root: "documents",
        path: "/Users/x/Documents",
        access: { kind: "denied", errno: 1 },
        recorded: false,
        note: null,
      } satisfies ProbeResult,
    });
    expect(body).toContain("macOS is refusing it");
  });
});

describe("access rules", () => {
  test("the launch-time probe fires only as a revocation check", () => {
    expect(launchActions(snapshot())).toEqual({ probe: null, postUpdateNotice: false });
    // In scope, never granted: Rust says `none`, and this must not second-guess it — a read here
    // would be an unexplained macOS prompt (plan R1, final-check M2).
    expect(
      launchActions(
        snapshot({
          roots: [{ key: "desktop", path: "/d", denied: [], because: ["/d"] }],
          probeAdvice: "none",
          probeRoot: null,
        }),
      ).probe,
    ).toBeNull();
    expect(
      launchActions(
        snapshot({
          roots: [{ key: "desktop", path: "/d", denied: [], because: ["/d"] }],
          grantObserved: true,
          probeAdvice: "revocation-check",
          probeRoot: "desktop",
        }),
      ).probe,
    ).toBe("desktop");
    // Unsupported platforms do nothing at all.
    expect(
      launchActions(
        snapshot({ supported: false, probeAdvice: "revocation-check", probeRoot: "desktop" }),
      ),
    ).toEqual({ probe: null, postUpdateNotice: false });
    // ⚠ THE INCONSISTENT PAIR (round 1: mutant M10 — `launchActions` ignoring `probeAdvice` —
    // survived, because every `"none"` fixture above also had `probeRoot: null`). Rust never
    // produces `none` WITH a root, but the mirror must fail closed on it: `probeAdvice` is the
    // gate, `probeRoot` is only the operand.
    expect(
      launchActions(snapshot({ probeAdvice: "none", probeRoot: "desktop" })).probe,
    ).toBeNull();
    // The post-update notice needs a root in scope to be actionable.
    expect(
      launchActions(snapshot({ versionChange: { kind: "changed", from: "0.1.0" } }))
        .postUpdateNotice,
    ).toBe(false);
    expect(
      launchActions(
        snapshot({
          versionChange: { kind: "changed", from: "0.1.0" },
          roots: [{ key: "desktop", path: "/d", denied: [], because: ["/d"] }],
        }),
      ).postUpdateNotice,
    ).toBe(true);
  });

  test("each read verdict gets its own sentence", () => {
    const at = (access: ProbeResult["access"]): string =>
      describeAccess({ root: "documents", path: "/d", access, recorded: false, note: null });
    expect(at({ kind: "ok", entries: 3 })).toContain("can read");
    expect(at({ kind: "denied", errno: 1 })).toContain("macOS is refusing it");
    expect(at({ kind: "notFound" })).toContain("does not exist");
    expect(at({ kind: "notADirectory" })).toContain("not a folder");
    expect(at({ kind: "error", detail: "errno-5" })).toContain("errno-5");
  });
});

/* ── T20: the verification loop ───────────────────────────────────────────────────────────────── */

describe("verify-flow", () => {
  const envelope = (
    extra: Partial<{
      kickstarted: boolean;
      outcome: string;
      skipReason: string | null;
      detail: string | null;
      iterations: number;
    }> = {},
  ) => ({
    kickstarted: true,
    outcome: "delivered",
    skipReason: null,
    detail: null,
    iterations: 1,
    ...extra,
  });

  test("a payload that is not a VerifyResult is not read as one", () => {
    expect(verifyEnvelope(null)).toBeNull();
    expect(verifyEnvelope({ outcome: "delivered" })).toBeNull();
    expect(verifyEnvelope({ kickstarted: true })).toBeNull();
    expect(verifyEnvelope(envelope())?.outcome).toBe("delivered");
  });

  test("a delivery ends the loop and falls through to the next-tick watch", () => {
    const stage = afterVerify(outcome({ payload: envelope() }), 1);
    expect(stage.stage).toBe("watching");
    expect(stage.stage === "watching" && stage.message).toContain("Confirmed");
    // ⚠ NO SECOND KICK. Plan R1 (final-check M3): a fresh install's first iteration may deliver a
    // THIN briefing, and `doctor`'s "repos need access" carries the thinness — retrying would
    // generate a second briefing for no new fact.
    expect(stage.stage).not.toBe("retrying");
  });

  test("a skip is confirmation that the trigger works, and loops to a bounded stop", () => {
    const skip = outcome({
      outcome: { kind: "delivered" },
      payload: envelope({ outcome: "skipped", skipReason: "offline", detail: "no network" }),
    });
    const first = afterVerify(skip, 1);
    expect(first.stage).toBe("retrying");
    expect(first.stage === "retrying" && first.attempt).toBe(2);
    expect(first.stage === "retrying" && first.message).toContain("offline");

    const last = afterVerify(skip, MAX_VERIFY_ATTEMPTS);
    expect(last.stage).toBe("stopped");
    expect(last.stage === "stopped" && last.message).toContain("the trigger works");
  });

  test("already-delivered-before-kick is NEVER rendered as a successful verification", () => {
    const stage = afterVerify(
      outcome({ payload: envelope({ outcome: "already-delivered-before-kick" }) }),
      1,
    );
    expect(stage.stage).toBe("stopped");
    const message = stage.stage === "stopped" ? stage.message : "";
    expect(message).toContain("Not confirmed");
    expect(message).not.toContain("Confirmed:");
    // And it is not retried: the day marker makes every further kick decline the same way.
    expect(stage.stage).not.toBe("retrying");
  });

  test("no evidence retries and then stops honestly", () => {
    const none = outcome({
      outcome: { kind: "failed", reason: null },
      exitCode: 1,
      payload: envelope({ outcome: "no-evidence" }),
    });
    expect(afterVerify(none, 1).stage).toBe("retrying");
    const stopped = afterVerify(none, MAX_VERIFY_ATTEMPTS);
    expect(stopped.stage).toBe("stopped");
    expect(stopped.stage === "stopped" && stopped.message).toContain("Not confirmed");
  });

  test("a refused kick and a missing envelope are both reported as refusals", () => {
    const refused = afterVerify(
      outcome({
        outcome: { kind: "failed", reason: "exit-3" },
        exitCode: 3,
        payload: envelope({ kickstarted: false }),
        stderr: "launchctl: could not kickstart",
      }),
      1,
    );
    expect(refused.stage).toBe("refused");
    expect(refused.stage === "refused" && refused.message).toContain("launchctl");

    const noEnvelope = afterVerify(
      outcome({ outcome: { kind: "failed", reason: "malformed-json" }, stderr: "boom" }),
      1,
    );
    expect(noEnvelope.stage).toBe("refused");
    expect(noEnvelope.stage === "refused" && noEnvelope.message).toBe("boom");
  });

  test("an outcome this version does not know is NOT a pass", () => {
    const stage = afterVerify(outcome({ payload: envelope({ outcome: "something-new" }) }), 1);
    expect(stage.stage).toBe("stopped");
    expect(stage.stage === "stopped" && stage.message).toContain("Not confirmed");
  });

  test("only a NEW skip record, or a delivery, counts as evidence", () => {
    expect(isNewEvidence({ skipIso: null, delivered: false }, null)).toBe(false);
    expect(isNewEvidence({ skipIso: "A", delivered: false }, "A")).toBe(false);
    expect(isNewEvidence({ skipIso: "B", delivered: false }, "A")).toBe(true);
    expect(isNewEvidence({ skipIso: "A", delivered: true }, "A")).toBe(true);
  });

  test("settled skip reasons end the loop with benign copy, never a retry", () => {
    // The engine's own settled set (`src/schedule/install.ts`): both PROVE the trigger reached
    // the engine, and neither is improved by another live kick. On a fresh install `already-ran`
    // is the INSTALL'S OWN first run, so it must not read as trouble.
    const already = afterVerify(
      outcome({ payload: envelope({ outcome: "skipped", skipReason: "already-ran" }) }),
      1,
    );
    expect(already.stage).toBe("watching");
    expect(already.stage === "watching" && already.message).toContain("Confirmed");
    expect(already.stage === "watching" && already.message).toContain("install's own first run");

    const floor = afterVerify(
      outcome({ payload: envelope({ outcome: "skipped", skipReason: "below-floor" }) }),
      1,
    );
    expect(floor.stage).toBe("watching");
    expect(floor.stage === "watching" && floor.message).toContain("Confirmed");

    // The additive rule cuts the other way for retries: a reason OUTSIDE the settled set —
    // including one this version does not know — may clear, so it keeps the bounded retry.
    const unknown = afterVerify(
      outcome({ payload: envelope({ outcome: "skipped", skipReason: "something-new" }) }),
      1,
    );
    expect(unknown.stage).toBe("retrying");
    expect(
      afterVerify(
        outcome({ payload: envelope({ outcome: "skipped", skipReason: "something-new" }) }),
        MAX_VERIFY_ATTEMPTS,
      ).stage,
    ).toBe("stopped");
  });

  /* ── the loop state machine (round 1 — the HIGH lived here) ────────────────────────────────── */

  const skipped = (reason: string): EngineOutcome =>
    outcome({ payload: envelope({ outcome: "skipped", skipReason: reason }) });

  test("a skip record produced by the loop's own kick is absorbed, in BOTH windows", () => {
    // Window 1: the watcher's push lands while the kick's IPC is still in flight.
    let s = beginKick({ skipIso: "A", delivered: false }, 1);
    let r = onEvidence(s, { skipIso: "B", delivered: false });
    expect(r.kick).toBeNull();
    expect(r.state.seenSkipIso).toBe("B");
    s = afterKick(r.state, skipped("offline"), 1, { skipIso: "B", delivered: false });
    expect(s.stage.stage).toBe("retrying");
    expect(s.ownSkipPending).toBe(false);
    // The record already accounted for does not re-arm…
    expect(onEvidence(s, { skipIso: "B", delivered: false }).kick).toBeNull();
    // …and the NEXT tick's record does.
    expect(onEvidence(s, { skipIso: "C", delivered: false }).kick).toBe(2);

    // Window 2: the push arrives only AFTER the loop has entered `retrying` (the ~250 ms debounce
    // usually beats the IPC return, but that ordering is NOT guaranteed). The engine's `skipped`
    // answer proves a record the app has not seen yet, so the FIRST new iso is the kick's own
    // output — absorbed — and only the one after it arms the next kick.
    s = beginKick({ skipIso: "A", delivered: false }, 1);
    s = afterKick(s, skipped("offline"), 1, { skipIso: "A", delivered: false });
    expect(s.stage.stage).toBe("retrying");
    expect(s.ownSkipPending).toBe(true);
    r = onEvidence(s, { skipIso: "B", delivered: false });
    expect(r.kick).toBeNull();
    expect(r.state.seenSkipIso).toBe("B");
    r = onEvidence(r.state, { skipIso: "C", delivered: false });
    expect(r.kick).toBe(2);
  });

  test("onEvidence agrees with isNewEvidence wherever the refinement is inert", () => {
    // Round 2: `isNewEvidence` is production-dead — round 1 moved the loop into `onEvidence`,
    // which REFINES the predicate (own-kick absorption, the predates-the-kick delivery rule)
    // instead of calling it — and its doc keeps it as "the table the refinement is judged
    // against". This is the judging, so the two cannot drift silently. In a PLAIN retrying state
    // (no own skip pending, no delivery on the books at kick) the refinements are inert, and
    // `onEvidence` must ACT — arm a kick, or confirm a delivery — exactly when `isNewEvidence`
    // says the push is new evidence, over the same evidence/baseline table.
    let s = beginKick({ skipIso: "A", delivered: false }, 1);
    s = afterKick(s, skipped("offline"), 1, { skipIso: "B", delivered: false });
    expect(s.stage.stage).toBe("retrying");
    expect(s.ownSkipPending).toBe(false);
    expect(s.deliveredAtKick).toBe(false);
    const table: VerifyEvidence[] = [
      { skipIso: null, delivered: false }, // nothing on the books — not evidence
      { skipIso: "B", delivered: false }, // already accounted for — not evidence
      { skipIso: "C", delivered: false }, // a new record — evidence (arms the kick)
      { skipIso: "B", delivered: true }, // a delivery — evidence (confirms, never kicks)
    ];
    for (const evidence of table) {
      const r = onEvidence(s, evidence);
      const acted = r.kick !== null || r.state !== s;
      expect(acted).toBe(isNewEvidence(evidence, s.seenSkipIso));
    }
  });

  test("a delivery during the loop ends it in watching — never a kick", () => {
    // While retrying…
    let s = beginKick({ skipIso: "A", delivered: false }, 1);
    s = afterKick(s, skipped("offline"), 1, { skipIso: "B", delivered: false });
    let r = onEvidence(s, { skipIso: "B", delivered: true });
    expect(r.kick).toBeNull();
    expect(r.state.stage.stage).toBe("watching");
    // …and while the kick is still in flight: the loop settles, and the LATE IPC answer (and a
    // late `busy` rejection) is dropped rather than un-confirming a delivery.
    s = beginKick({ skipIso: "A", delivered: false }, 1);
    r = onEvidence(s, { skipIso: "A", delivered: true });
    expect(r.kick).toBeNull();
    expect(r.state.stage.stage).toBe("watching");
    expect(afterKick(r.state, skipped("offline"), 1, { skipIso: "A", delivered: true }).stage.stage).toBe(
      "watching",
    );
    expect(afterKickRefusal(r.state, "busy").stage.stage).toBe("watching");
  });

  test("a delivery that PREDATES the kick is not read as the loop's confirmation", () => {
    // A manual check while today's briefing is already on the books: §3 — already-delivered is
    // never a success, and the kick's own envelope (`already-delivered-before-kick`) is the honest
    // answer, so the push must not preempt it.
    const s = beginKick({ skipIso: "A", delivered: true }, 1);
    const r = onEvidence(s, { skipIso: "A", delivered: true });
    expect(r.kick).toBeNull();
    expect(r.state.stage.stage).toBe("verifying");
  });

  test("arming the loop with a delivery already on the books confirms WITHOUT a kick", () => {
    // Plan R1 (final-check M3), directly: the install's own kickstart delivered, so the panel
    // watches — it does not issue a live kick whose only possible answers restate what is known.
    const armed = armLoop({ skipIso: "A", delivered: true });
    expect(armed.kick).toBeNull();
    expect(armed.state.stage.stage).toBe("watching");
    expect(armed.state.stage.stage === "watching" && armed.state.stage.message).toContain(
      "Confirmed",
    );
    const kicked = armLoop({ skipIso: "A", delivered: false });
    expect(kicked.kick).toBe(1);
    expect(kicked.state.stage.stage).toBe("verifying");
  });

  test("the evidence fold is a fixed point, so a reactive caller cannot loop on it", () => {
    // `onEvidence` returns the SAME object when nothing changed — the component's `$effect`
    // compares by reference. After any change it applies, folding the same evidence again must
    // change nothing and kick nothing.
    const idle = { skipIso: null, delivered: false };
    let s = beginKick(idle, 1);
    expect(onEvidence(s, idle).state).toBe(s);
    const pushed = { skipIso: "B", delivered: false };
    let r = onEvidence(s, pushed);
    expect(onEvidence(r.state, pushed).state).toBe(r.state);
    const delivered = { skipIso: "B", delivered: true };
    r = onEvidence(s, delivered);
    expect(onEvidence(r.state, delivered).state).toBe(r.state);
    expect(onEvidence(r.state, delivered).kick).toBeNull();
  });

  test("the control says what it will do before it does it", () => {
    const body = html(ScheduleVerify, { evidence: { skipIso: null, delivered: false } });
    expect(buttons(body)).toEqual(["Check the background scheduler now"]);
    expect(body).toContain("It can generate today's briefing.");
  });
});

/* ── T20: the removal ─────────────────────────────────────────────────────────────────────────── */

describe("uninstall-flow", () => {
  const PLIST = "/Users/x/Library/LaunchAgents/local.daily-briefing.plist";
  const TIMER = "/home/x/.config/systemd/user/daily-briefing.timer";
  // The engine's manual steps open with this line (`src/schedule/install.ts`, `manualRemoveSteps`; the
  // static copies' pin in `coexistence.check.ts` holds the app's copy of it to the engine's text).
  const STEPS = [
    "Run these in a terminal (bash or zsh) inside your desktop session.",
    "1. Unregister the job:",
    "   launchctl bootout gui/$(id -u)/local.daily-briefing; launchctl bootout user/$(id -u)/local.daily-briefing",
    "4. Delete the files:",
    `   rm -f -- "$HOME"/'Library/LaunchAgents/local.daily-briefing.plist'`,
  ].join("\n");
  const CLOSING = "Then press Remove again, or run Uninstall again.";
  const TODAYS_LEAD = "Something else already owns the background schedule.";
  const NULL_OWNER_LEAD = "A background scheduler is set up, but nothing records who set it up.";
  /** `schedule uninstall --invoker app`'s outcome as Rust classifies each exit (`engine.rs`, `classify`). */
  const removal = (exitCode: number | null, stderr = "", stdout = ""): EngineOutcome =>
    outcome({
      operation: "schedule-uninstall",
      outcome:
        exitCode === 0
          ? { kind: "delivered" }
          : exitCode === 2
            ? { kind: "configError" }
            : { kind: "failed", reason: exitCode === 1 ? null : exitCode === null ? "signalled" : `exit-${exitCode}` },
      exitCode,
      stdout,
      stderr,
    });
  /** The app's refusal (spec 3.1.1), naming what the engine found. */
  const refusal = (found: string): EngineOutcome =>
    removal(2, `This background scheduler wasn't set up by this app (${found}). Removing it needs your go-ahead.\n`);
  const source = (file: string): Promise<string> =>
    Bun.file(new URL(`../src/lib/${file}`, import.meta.url)).text();

  test("the confirmation names the unit file it removes, what stops by its label, and the consequence", () => {
    const c = uninstallConfirmation(scheduleState(), "macos");
    expect(c.unitPath).toBe(PLIST);
    expect(c.body).toContain(PLIST);
    expect(c.body).toContain("unloads the loaded job `local.daily-briefing`");
    expect(c.body).toContain("Nothing will generate a briefing after that");
    expect(c.body).toContain("archive are untouched");
    // Checkpoint M6b (F5): exactly what the component draws — no `foreign` flag, which nothing read
    // (the ownership sentence in `body` is what says a second confirmation follows).
    expect(Object.keys(c).sort()).toEqual(["body", "confirmLabel", "owner", "title", "unitPath"]);
    // Checkpoint M6a: unregistering is a `bootout` by label, not an unload of whatever the file names.
    expect(c.body).not.toContain("unloads it from the operating system");
    const linux = uninstallConfirmation(scheduleState({ unitPath: TIMER }), "linux");
    expect(linux.body).toContain(TIMER);
    expect(linux.body).toContain("stops the `daily-briefing` timer and service");
  });

  test("with no unit file it names no path — not even the computed one — and says what it stops, per platform (spec 3.4.8)", () => {
    // `unitPath` is the engine's COMPUTED default when no unit file is there (`status.ts`).
    const noFile = (unitPath: string | null) => scheduleState({ unitPresent: false, unitPath });
    const mac = uninstallConfirmation(noFile(PLIST), "macos");
    expect(mac.unitPath).toBeNull();
    expect(mac.body).not.toContain(PLIST);
    expect(mac.body).toContain("This unloads the loaded job `local.daily-briefing`.");
    const linux = uninstallConfirmation(noFile(TIMER), "linux");
    expect(linux.unitPath).toBeNull();
    expect(linux.body).not.toContain(TIMER);
    expect(linux.body).toContain("This stops the `daily-briefing` timer and service.");
    // Off launchd and systemd: the plain words, still no path.
    for (const os of ["windows", "other"] as const) {
      const other = uninstallConfirmation(noFile("C:\\x\\task.xml"), os);
      expect(other.body).not.toContain("C:\\x\\task.xml");
      expect(other.body).toContain("This unregisters the background scheduler from the operating system.");
    }
    // No path reported at all: the same.
    expect(uninstallConfirmation(scheduleState({ unitPath: null }), "macos").unitPath).toBeNull();
    expect(uninstallConfirmation(scheduleState({ unitPath: null }), "macos").body).toContain(
      "This unloads the loaded job `local.daily-briefing`.",
    );
  });

  test("checkpoint M6b (F3): on macOS it says \"unloads the loaded job\" only when the job may be loaded — registered true or unknown — and \"if it is still loaded\" when the check found none (spec 3.4.8)", () => {
    const LOADED = "unloads the loaded job `local.daily-briefing`";
    const IF_LOADED = "unregisters `local.daily-briefing` if it is still loaded";
    const mac = (extra: Partial<ScheduleState>) => uninstallConfirmation(scheduleState(extra), "macos").body;
    // Registered, or the check could not say: the spec's own wording, with the file and without.
    for (const registered of [true, null]) {
      expect([registered, mac({ registered })]).toEqual([
        registered,
        expect.stringContaining(`This removes the background scheduler's trigger file, ${PLIST}, and ${LOADED}.`),
      ]);
      expect([registered, mac({ registered, unitPresent: false })]).toEqual([
        registered,
        expect.stringContaining(`This ${LOADED}.`),
      ]);
      expect([registered, mac({ registered }).includes(IF_LOADED)]).toEqual([registered, false]);
    }
    // The check found nothing registered (a record or a unit file with nothing loaded — the
    // scheduler-broken phase with its unit there): no loaded job is claimed.
    const withFile = mac({ registered: false });
    expect(withFile).toContain(`This removes the background scheduler's trigger file, ${PLIST}, and ${IF_LOADED}.`);
    expect(withFile).not.toContain(LOADED);
    const noFile = mac({ registered: false, unitPresent: false, recordFilePresent: true });
    expect(noFile).toContain(`This ${IF_LOADED}.`);
    expect(noFile).not.toContain(LOADED);
    expect(noFile).not.toContain(PLIST);
    // No state read at all (M9 round 2): nothing is known, so no loaded job is claimed — M6b(2)'s form. (A
    // state whose check could not run, `registered: null`, keeps the spec's wording above.)
    expect(uninstallConfirmation(null, "macos").body).toContain(`This ${IF_LOADED}.`);
    expect(uninstallConfirmation(null, "macos").body).not.toContain(LOADED);
    // Linux and the rest are unchanged by registration: they claim nothing is loaded.
    for (const registered of [true, false, null]) {
      expect(uninstallConfirmation(scheduleState({ registered, unitPath: TIMER }), "linux").body).toContain(
        "and stops the `daily-briefing` timer and service.",
      );
      expect(uninstallConfirmation(scheduleState({ registered, unitPresent: false }), "other").body).toContain(
        "This unregisters the background scheduler from the operating system.",
      );
    }
  });

  test("a CLI-owned schedule warns that removing it needs a second confirmation", () => {
    const c = uninstallConfirmation(scheduleState({ owner: "cli", invoker: "cli" }), "macos");
    expect(c.body).toContain("installed from the command line");
    expect(c.body).toContain("removing it needs a second confirmation.");
  });

  test("a null owner gets its own wording, never the terminal's (spec 3.4.3)", () => {
    for (const unitPresent of [true, false]) {
      const c = uninstallConfirmation(scheduleState({ owner: null, invoker: null, recordPresent: false, unitPresent }), "macos");
      expect(c.body).toContain("Nothing records who set up this background scheduler.");
      expect(c.body).not.toContain("command line");
      // The engine refuses `--invoker app` without a record owned by `app` (spec 3.1.1), so the
      // take-over question follows here too — and the body says so.
      expect(c.body).toContain("Removing it needs a second confirmation.");
    }
    // This app's own: no ownership sentence at all.
    const own = uninstallConfirmation(scheduleState(), "macos").body;
    expect(own).not.toContain("Nothing records who set up");
    expect(own).not.toContain("second confirmation");
  });

  test("M9 round 2: with NO state read, the confirmation makes no claim from it — no ownership sentence (owner unknown is not owner absent), no loaded job — and the foreign-owner dialog keeps its default lead", () => {
    const LOADED = "unloads the loaded job `local.daily-briefing`";
    // The remove control can be drawn with no state since M9 round 1 (a failed removal, then a refresh that
    // read nothing). Nothing is known then: an app-owned scheduler would get no second confirmation, so the
    // body must not promise one, nor say nothing records who set it up.
    for (const os of ["macos", "linux", "windows", "other"] as const) {
      const c = uninstallConfirmation(null, os);
      expect([os, c.body.includes("Nothing records who set up")]).toEqual([os, false]);
      expect([os, c.body.includes("second confirmation")]).toEqual([os, false]);
      expect([os, c.body.includes("command line")]).toEqual([os, false]);
      expect([os, c.body.includes(LOADED)]).toEqual([os, false]);
      expect([os, c.unitPath, c.owner]).toEqual([os, null, null]);
    }
    expect(uninstallConfirmation(null, "macos").body).toBe(
      "This unregisters `local.daily-briefing` if it is still loaded. Nothing will generate a briefing after that — not on a timer, and not while this app is open — until a scheduler is installed again. Your config, your settings and every briefing already in the archive are untouched.",
    );
    // A state that READ no owner still gets its own wording: that is a fact, not an unknown.
    expect(uninstallConfirmation(scheduleState({ owner: null, invoker: null, recordPresent: false }), "macos").body).toContain(
      "Nothing records who set up this background scheduler.",
    );

    // After an exit 2, the dialog with no state is drawn with ForeignOwnerDialog's default lead, never the
    // null-owner one; with a state whose owner is null, the null-owner lead as before.
    const dialogLead = (scheduleState: ScheduleState | null): string => {
      const body = html(ScheduleUninstall, { scheduleState, os: "macos", stage: "foreign-owner" });
      return /<p class="lead[^"]*">([\s\S]*?)<\/p>/.exec(body)?.[1]?.trim() ?? "";
    };
    expect(dialogLead(null)).toBe(TODAYS_LEAD);
    expect(dialogLead(scheduleState({ owner: null, invoker: null, recordPresent: false }))).toBe(NULL_OWNER_LEAD);
    expect(dialogLead(scheduleState({ owner: "cli", invoker: "cli" }))).toBe(TODAYS_LEAD);
  });

  test("exit 1 shows the engine's own stdout line; exit 1 with empty stdout is a crash, shown as failed with its stderr (spec 3.4.7; SQ1)", () => {
    // ⚠ `reason` IS NULL HERE — gui-seam §3: the classifier invents no reason string for exit 1, so
    // the key is the exit code.
    const genuine = afterUninstall(removal(1, "", "Nothing installed by daily-briefing was found.\n"), false);
    expect(genuine).toEqual({ stage: "done", message: "Nothing installed by daily-briefing was found." });
    // The engine's words, whatever they are — never the app's old fixed sentence.
    expect(afterUninstall(removal(1, "", "Some other wording.\n"), false)).toEqual({
      stage: "done",
      message: "Some other wording.",
    });
    expect(genuine.message).not.toContain("nothing to remove");
    // A crash before the engine's own try block exits 1 with only stderr (spec §2 point 17).
    const crash = afterUninstall(removal(1, "TypeError: boom\n    at main (main.ts:1:1)\n", ""), false);
    // Its stderr verbatim (checkpoint M6b, F1): the trailing line break included.
    expect(crash).toEqual({ stage: "failed", message: "TypeError: boom\n    at main (main.ts:1:1)\n" });
    expect(afterUninstall(removal(1, "boom\n", "  \n"), false).stage).toBe("failed");
    // Nothing on either stream: failed, and the line says so in the app's words.
    const silent = afterUninstall(removal(1), false);
    expect(silent).toEqual({ stage: "failed", message: "" });
    expect(uninstallLine(silent)).toEqual({ kind: "failed", line: "That did not work.", closing: null });
  });

  test("every exit 2 without take-over is the foreign-owner stage, whatever owner the screen last read — cli, null or a stale app — and carries the engine's stderr (spec 3.4.3; SQ1)", () => {
    const found = refusal(
      "a schedule record that can't be read at /Users/x/Library/Application Support/daily-briefing/schedule.json, with no unit file",
    );
    const expected = {
      stage: "foreign-owner",
      message:
        "This background scheduler wasn't set up by this app (a schedule record that can't be read at /Users/x/Library/Application Support/daily-briefing/schedule.json, with no unit file). Removing it needs your go-ahead.\n",
    };
    expect(afterUninstall(found, false)).toEqual(expected);
    // The cached owner is not an input: Uninstall has no confirmation gate, so its exit 2 only ever means
    // "not yours", and the owner the screen last read can be stale. What it still decides is the lead.
    expect(afterUninstall.length).toBe(2);
    for (const [owner, lead] of [
      ["cli", undefined],
      [null, NULL_OWNER_LEAD],
      ["app", undefined],
    ] as const) {
      expect([owner, afterUninstall(found, false), foreignOwnerLead(owner)]).toEqual([owner, expected, lead]);
    }
    // Already took over and still refused: a failure, never a second dialog.
    expect(afterUninstall(found, true)).toEqual({ ...expected, stage: "failed" });
  });

  test("the component asks with the engine's words, the cached owner's lead, and no owner rule of its own", async () => {
    const component = await source("ScheduleUninstall.svelte");
    expect(component).toContain("const next = afterUninstall(outcome, takeOver);");
    // M9 round 2: with no state read, `undefined` — the dialog's default lead — never the null-owner one.
    expect(component).toMatch(
      /<ForeignOwnerDialog\s+\{message\}\s+lead=\{scheduleState === null \? undefined : foreignOwnerLead\(scheduleState\.owner\)\}\s+purpose="remove the background scheduler"/,
    );
    // "Keep the existing one" ends the flow with the helper's line.
    expect(component).toContain("onkeep={() => settle(afterKeep())}");
  });

  test("the dialog, as the removal draws it: the null-owner lead for a null owner, today's for a cached cli one, the unit path a take-over removes, Keep first (spec 3.4.3)", () => {
    const dialog = (owner: string | null, found: string): string => {
      const next = afterUninstall(refusal(found), false);
      expect(next.stage).toBe("foreign-owner");
      return html(ForeignOwnerDialog, {
        message: next.message,
        lead: foreignOwnerLead(owner),
        purpose: "remove the background scheduler",
        onkeep: () => {},
        ontakeover: () => {},
      });
    };
    // A unit with no record: the dialog names the unit file that taking over removes.
    const unitOnly = dialog(null, `the unit file ${PLIST}, with no schedule record`);
    expect(unitOnly).toContain(NULL_OWNER_LEAD);
    expect(unitOnly).not.toContain(TODAYS_LEAD);
    expect(unitOnly).toContain(`the unit file ${PLIST}, with no schedule record`);
    expect(buttons(unitOnly)).toEqual(["Keep the existing one", "Take over and remove the background scheduler"]);
    // A registration with no files: what the engine found, verbatim.
    expect(dialog(null, "a loaded job with no files")).toContain("(a loaded job with no files)");
    // A cached terminal owner keeps today's lead.
    const cli = dialog("cli", `a schedule record set up from the terminal at /x/schedule.json, and the unit file ${PLIST}`);
    expect(cli).toContain(TODAYS_LEAD);
    expect(cli).not.toContain(NULL_OWNER_LEAD);
    expect(cli).toContain(PLIST);
    // Engine text stays text.
    expect(dialog(null, HOSTILE)).not.toContain("<img");
  });

  test("\"Keep the existing one\" ends with \"Kept — nothing was removed.\" (spec 3.4.5)", () => {
    expect(afterKeep()).toEqual({ stage: "done", message: "Kept — nothing was removed." });
    expect(uninstallLine(afterKeep())).toEqual({ kind: "done", line: "Kept — nothing was removed.", closing: null });
  });

  test("exit 3 shows the engine's stderr verbatim, with Try again; manual steps get the app's closing line once, after them (spec 3.4.6; SQ6)", () => {
    // Not gone in time: the details, then the steps (spec 3.1.7).
    const late = [
      "The background scheduler is still registered after 30 seconds.",
      "Still on this computer: the registered job local.daily-briefing.",
      "This attempt removed nothing.",
      STEPS,
    ].join("\n");
    // A stable reason: the steps FIRST, then the details.
    const stable = [STEPS, "Couldn't check whether a background scheduler is registered (no-gui-session). Nothing was removed."].join("\n");
    for (const stderr of [late, stable]) {
      for (const takeOver of [false, true]) {
        const next = afterUninstall(removal(3, `${stderr}\n`), takeOver);
        // Verbatim (checkpoint M6b, F1): the engine's closing line break is kept, not trimmed.
        expect(next).toEqual({ stage: "failed", message: `${stderr}\n` });
        const line = uninstallLine(next);
        expect(line).toEqual({ kind: "failed", line: `${stderr}\n`, closing: CLOSING });
        // Once, and the app's own — never folded into the engine's text.
        expect(line?.line).not.toContain(CLOSING);
      }
    }
    expect(uninstallLine(afterUninstall(removal(3, `${stable}\n`), false))?.line.startsWith(STEPS.split("\n")[0] ?? "?")).toBe(
      true,
    );
    // An exit 3 that carries no steps gets no closing line.
    const bare = afterUninstall(removal(3, "schedule uninstall: no scheduler is supported on sunos.\n"), false);
    expect(uninstallLine(bare)).toEqual({
      kind: "failed",
      line: "schedule uninstall: no scheduler is supported on sunos.\n",
      closing: null,
    });
    // A signal death or any other code: failed, with what the engine said.
    expect(afterUninstall(removal(null, "killed\n"), false)).toEqual({ stage: "failed", message: "killed\n" });
    expect(afterUninstall(removal(4, "", "only stdout\n"), false)).toEqual({ stage: "failed", message: "only stdout" });
  });

  test("checkpoint M6b (F1): the engine's stderr reaches the stage and the line byte for byte — leading whitespace and trailing line breaks included (spec 3.4.3, 3.4.6)", () => {
    const stderr = `  \n\t  The background scheduler is still registered after 30 seconds.\n${STEPS}\n\n`;
    // Exit 3, with and without take-over, and a crash's exit 1: failed, the string untouched.
    for (const takeOver of [false, true]) {
      expect(afterUninstall(removal(3, stderr), takeOver)).toEqual({ stage: "failed", message: stderr });
      expect(uninstallLine(afterUninstall(removal(3, stderr), takeOver))).toEqual({ kind: "failed", line: stderr, closing: CLOSING });
    }
    expect(afterUninstall(removal(1, stderr), false)).toEqual({ stage: "failed", message: stderr });
    expect(afterUninstall(removal(null, stderr), false)).toEqual({ stage: "failed", message: stderr });
    // Exit 2: the foreign-owner stage carries it untouched too, and a refused take-over fails with it.
    const refused = `\n  This background scheduler wasn't set up by this app (a loaded job with no files).\n\n`;
    expect(afterUninstall(removal(2, refused), false)).toEqual({ stage: "foreign-owner", message: refused });
    expect(afterUninstall(removal(2, refused), true)).toEqual({ stage: "failed", message: refused });
    // A stderr of only whitespace said nothing: the fallbacks apply as before — stdout, then the app's word.
    expect(afterUninstall(removal(3, " \n\n", "only stdout\n"), false)).toEqual({ stage: "failed", message: "only stdout" });
    expect(uninstallLine(afterUninstall(removal(3, " \n\n"), false))).toEqual({ kind: "failed", line: "That did not work.", closing: null });
    expect(afterUninstall(removal(1, "\n"), false)).toEqual({ stage: "failed", message: "" });
  });

  test("a failed attempt offers Try again, which repeats it; nothing else does", async () => {
    const drawn = (stage: string) => buttons(html(ScheduleUninstall, { scheduleState: scheduleState(), os: "macos", stage }));
    expect(drawn("failed")).toEqual(["Remove background scheduler…", "Try again"]);
    for (const stage of ["idle", "done", "foreign-owner"]) {
      expect(drawn(stage).includes("Try again")).toBe(false);
    }
    const component = await source("ScheduleUninstall.svelte");
    expect(component).toMatch(/onclick=\{\(\) => remove\(lastTakeOver\)\}>Try again<\/button>/);
    expect(component).toMatch(/async function remove\(takeOver: boolean\): Promise<void> \{[\s\S]*?lastTakeOver = takeOver;/);
  });

  test("done and failed say so in one line, with the engine's words or the app's own", () => {
    expect(uninstallLine(afterUninstall(removal(0, "", "Removed the background scheduler.\n"), false))).toEqual({
      kind: "done",
      line: "Removed the background scheduler.",
      closing: null,
    });
    expect(uninstallLine({ stage: "done", message: "" })).toEqual({ kind: "done", line: "Removed.", closing: null });
    for (const stage of ["idle", "running", "foreign-owner"] as const) {
      expect(uninstallLine({ stage, message: "x" })).toBeNull();
    }
  });

  test("the first control is the confirmation, not the removal", () => {
    const body = html(ScheduleUninstall, { scheduleState: scheduleState(), os: "macos" });
    expect(buttons(body)).toEqual(["Remove background scheduler…"]);
    // The destructive label and the consequence are behind it, not on the screen by default.
    expect(body).not.toContain("Nothing will generate a briefing after that");
  });
});
