/**
 * B6 — T17's folder-access flow and T20's verification / removal rules, rendered by the real Svelte
 * compiler and asserted as markup, plus the pure modules behind them.
 *
 * ⚠ THE GOLDEN FOR THE ADVICE TEXT IS THE ENGINE ITSELF. `warnFor` is imported READ-ONLY from
 * `src/protectedPath.ts` — the same shared-fixture discipline `briefing.check.ts` uses for
 * `renderBriefing` — because appendix T17 requires the engine's advice *"displayed unmodified"* and
 * a checked-in copy of that sentence would drift the moment the engine reworded it. The fixture is
 * generated by CALLING the engine function; nothing here re-spells it.
 *
 * ⚠ NOTHING HERE TOUCHES A REAL PROTECTED FOLDER, opens anything, or reaches the engine: SSR
 * renders markup and runs no click handler (`docs/gui-seam.md` §10f), and every rule under test is
 * a pure function over data this file constructs.
 */
import { describe, expect, test } from "bun:test";
import { render } from "svelte/server";

// READ-ONLY import of the engine's own advice writer. `protectedPath.ts` imports only `node:os` and
// `node:path` and has no Bun-only API, so it loads here directly.
import { warnFor } from "../../src/protectedPath";
import ScheduleAccess from "../src/lib/ScheduleAccess.svelte";
import ScheduleUninstall from "../src/lib/ScheduleUninstall.svelte";
import ScheduleVerify from "../src/lib/ScheduleVerify.svelte";
import { describeAccess, launchActions, type AccessSnapshot, type ProbeResult } from "../src/lib/access";
import { afterUninstall, uninstallConfirmation } from "../src/lib/uninstall-flow";
import {
  afterKick,
  afterKickRefusal,
  afterVerify,
  armLoop,
  beginKick,
  isNewEvidence,
  MAX_VERIFY_ATTEMPTS,
  onEvidence,
  verifyEnvelope,
  type VerifyEvidence,
} from "../src/lib/verify-flow";
import type { EngineOutcome } from "../src/lib/engine";
import type { ScheduleState } from "../src/lib/state";

const HOSTILE = '<img src=x onerror="alert(1)">';

function html(component: unknown, props: Record<string, unknown>): string {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return render(component as any, { props })
    .body.replace(/<!--[\s\S]*?-->/g, "")
    .replace(/\s+/g, " ");
}

function buttons(body: string): string[] {
  return [...body.matchAll(/<button[^>]*>([\s\S]*?)<\/button>/g)].map((m) => (m[1] ?? "").trim());
}

/**
 * The five entities Svelte's escaper emits, turned back into the characters they stand for.
 *
 * ⚠ THE ESCAPING IS THE PROOF, NOT AN OBSTACLE. The engine's advice contains `&` (in "Privacy &
 * Security" and "Files & Folders"), which reaches the markup as `&amp;` precisely because the
 * string is drawn as a TEXT NODE rather than as markup. Comparing the decoded text is what
 * "verbatim" means here; comparing the raw markup would assert the opposite of what this app wants.
 */
function decode(text: string): string {
  return text
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&amp;/g, "&");
}

function snapshot(extra: Partial<AccessSnapshot> = {}): AccessSnapshot {
  return {
    supported: true,
    roots: [],
    doctorVerdict: "ready",
    reposTimedOut: false,
    grantObserved: false,
    probeAdvice: "none",
    probeRoot: null,
    versionChange: { kind: "same" },
    appVersion: "0.1.1",
    managedEnginePath: null,
    notes: [],
    ...extra,
  };
}

function outcome(extra: Partial<EngineOutcome> = {}): EngineOutcome {
  return {
    operation: "schedule-verify",
    outcome: { kind: "delivered" },
    exitCode: 0,
    payload: null,
    stdout: "",
    stderr: "",
    ...extra,
  };
}

function scheduleState(extra: Partial<ScheduleState> = {}): ScheduleState {
  return {
    phase: { phase: "waiting-for-wake" },
    statusLine: "Waiting",
    floor: "07:20",
    floorWarning: null,
    firstWake: "first wake",
    ticksToday: 3,
    ticksExpectedSinceFloor: 3,
    lastTick: null,
    owner: "app",
    invoker: "app",
    unitPath: "/Users/x/Library/LaunchAgents/local.daily-briefing.plist",
    registered: true,
    recordPresent: true,
    unitPresent: true,
    engineVersion: "0.1.1",
    installedEngineVersion: "0.1.1",
    engineUpdateAvailable: false,
    intervalSec: 600,
    experimental: false,
    lingerState: "not-applicable",
    ...extra,
  };
}

/* ── T17: the panel ───────────────────────────────────────────────────────────────────────────── */

describe("ScheduleAccess.svelte", () => {
  test("off macOS the whole step is absent", () => {
    const body = html(ScheduleAccess, { snapshot: snapshot({ supported: false }) });
    expect(body.trim()).toBe("");
    // And before the first snapshot there is nothing either — no half-rendered flow.
    expect(html(ScheduleAccess, { snapshot: null }).trim()).toBe("");
  });

  test("with nothing protected in scope it says so and offers no grant step", () => {
    const body = html(ScheduleAccess, { snapshot: snapshot() });
    expect(body).toContain("None of the folders your briefing reads is one macOS protects");
    expect(body).not.toContain("This app");
    expect(body).not.toContain("The background copy of the engine");
    // The panel is still available — plan R1 makes it always reachable — so Re-check is there.
    expect(buttons(body)).toEqual(["Re-check"]);
  });

  test("the engine's advice is rendered VERBATIM, generated by calling warnFor", () => {
    // The fixture IS the engine's output for this issue.
    const advice = warnFor({
      path: "/Users/x/Documents/proj",
      kind: "tcc-denied",
      protectedRoot: "/Users/x/Documents",
    });
    expect(advice).toContain("TCC-blocked");
    const body = html(ScheduleAccess, {
      snapshot: snapshot({
        roots: [
          {
            key: "documents",
            path: "/Users/x/Documents",
            denied: [{ path: "/Users/x/Documents/proj", advice }],
            because: ["/Users/x/Documents/proj"],
          },
        ],
      }),
    });
    // ⚠ EQUALITY, NOT CONTAINMENT, over the advice block's own text. A `toContain` would pass for a
    // panel that appended its own sentence to the engine's — which is exactly what "displayed
    // unmodified" forbids. Whitespace is collapsed on both sides (`html()` does it to the markup
    // and the engine writes the advice as one line, so this changes nothing about it).
    const rendered = /<pre class="advice[^"]*">([\s\S]*?)<\/pre>/.exec(body);
    expect(rendered).not.toBeNull();
    expect(decode((rendered?.[1] ?? "").trim())).toBe(advice.replace(/\s+/g, " "));
    // Both principals are guided — SPK-1(b)'s inheritance leg is UNRUN, so neither is assumed.
    expect(body).toContain("1. This app");
    expect(body).toContain("2. The background copy of the engine");
  });

  test("both System Settings panes are offered, with what each grants, and the manual fallback", () => {
    const body = html(ScheduleAccess, {
      snapshot: snapshot({
        managedEnginePath: "/Users/x/Library/Application Support/daily-briefing/daily-briefing",
        roots: [
          { key: "desktop", path: "/Users/x/Desktop", denied: [], because: ["/Users/x/Desktop"] },
        ],
      }),
    });
    const labels = buttons(body);
    expect(labels).toContain("Open Files &amp; Folders settings");
    expect(labels).toContain("Open Full Disk Access settings");
    expect(labels).toContain("Open Privacy &amp; Security");
    expect(labels).toContain("Show it in Finder");
    // Honest about what each one grants.
    expect(body).toContain("one protected folder at a time");
    expect(body).toContain("everything on the Mac");
    // The deep links are UNVERIFIED on macOS 26, so the manual path is always shown — not revealed
    // on failure, because a link that lands on the wrong pane reports no error.
    expect(body).toContain("If the button opens the wrong page");
    expect(body).toContain("x-apple.systempreferences:com.apple.preference.security?Privacy_Files");
    expect(body).toContain(
      "x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles",
    );
    // And the managed copy is named, because that is the file the user has to drag in.
    expect(body).toContain("/Users/x/Library/Application Support/daily-briefing/daily-briefing");
  });

  test("with no managed copy the reveal is disabled and says why", () => {
    const body = html(ScheduleAccess, {
      snapshot: snapshot({
        roots: [
          { key: "desktop", path: "/Users/x/Desktop", denied: [], because: ["/Users/x/Desktop"] },
        ],
      }),
    });
    expect(body).toContain("No background scheduler is installed yet");
    expect(body).toMatch(/<button[^>]*disabled[^>]*>\s*Show it in Finder/);
  });

  test("a new app version says macOS asks again after an update", () => {
    const body = html(ScheduleAccess, {
      snapshot: snapshot({
        versionChange: { kind: "changed", from: "0.1.0" },
        roots: [
          { key: "desktop", path: "/Users/x/Desktop", denied: [], because: ["/Users/x/Desktop"] },
        ],
      }),
    });
    expect(body).toContain("macOS asks for folder access again after an update");
    // …and not when nothing protected is in scope: a warning with no action.
    const none = html(ScheduleAccess, {
      snapshot: snapshot({ versionChange: { kind: "changed", from: "0.1.0" } }),
    });
    expect(none).not.toContain("macOS asks for folder access again");
  });

  test("every engine-supplied string stays literal text", () => {
    const body = html(ScheduleAccess, {
      snapshot: snapshot({
        managedEnginePath: HOSTILE,
        notes: [HOSTILE],
        roots: [
          {
            key: "documents",
            path: HOSTILE,
            denied: [{ path: HOSTILE, advice: HOSTILE }],
            because: [HOSTILE],
          },
        ],
      }),
      launchProbe: {
        root: "documents",
        path: HOSTILE,
        access: { kind: "denied", errno: 1 },
        recorded: false,
        note: HOSTILE,
      } satisfies ProbeResult,
    });
    expect(body).not.toContain("<img");
    expect(body).toContain("&lt;img");
  });

  test("the launch check's result is shown until the panel runs one of its own", () => {
    const body = html(ScheduleAccess, {
      snapshot: snapshot({
        roots: [
          {
            key: "documents",
            path: "/Users/x/Documents",
            denied: [],
            because: ["/Users/x/Documents"],
          },
        ],
      }),
      launchProbe: {
        root: "documents",
        path: "/Users/x/Documents",
        access: { kind: "denied", errno: 1 },
        recorded: false,
        note: null,
      } satisfies ProbeResult,
    });
    expect(body).toContain("macOS is refusing it");
  });
});

describe("access rules", () => {
  test("the launch-time probe fires only as a revocation check", () => {
    expect(launchActions(snapshot())).toEqual({ probe: null, postUpdateNotice: false });
    // In scope, never granted: Rust says `none`, and this must not second-guess it — a read here
    // would be an unexplained macOS prompt (plan R1, final-check M2).
    expect(
      launchActions(
        snapshot({
          roots: [{ key: "desktop", path: "/d", denied: [], because: ["/d"] }],
          probeAdvice: "none",
          probeRoot: null,
        }),
      ).probe,
    ).toBeNull();
    expect(
      launchActions(
        snapshot({
          roots: [{ key: "desktop", path: "/d", denied: [], because: ["/d"] }],
          grantObserved: true,
          probeAdvice: "revocation-check",
          probeRoot: "desktop",
        }),
      ).probe,
    ).toBe("desktop");
    // Unsupported platforms do nothing at all.
    expect(
      launchActions(
        snapshot({ supported: false, probeAdvice: "revocation-check", probeRoot: "desktop" }),
      ),
    ).toEqual({ probe: null, postUpdateNotice: false });
    // ⚠ THE INCONSISTENT PAIR (round 1: mutant M10 — `launchActions` ignoring `probeAdvice` —
    // survived, because every `"none"` fixture above also had `probeRoot: null`). Rust never
    // produces `none` WITH a root, but the mirror must fail closed on it: `probeAdvice` is the
    // gate, `probeRoot` is only the operand.
    expect(
      launchActions(snapshot({ probeAdvice: "none", probeRoot: "desktop" })).probe,
    ).toBeNull();
    // The post-update notice needs a root in scope to be actionable.
    expect(
      launchActions(snapshot({ versionChange: { kind: "changed", from: "0.1.0" } }))
        .postUpdateNotice,
    ).toBe(false);
    expect(
      launchActions(
        snapshot({
          versionChange: { kind: "changed", from: "0.1.0" },
          roots: [{ key: "desktop", path: "/d", denied: [], because: ["/d"] }],
        }),
      ).postUpdateNotice,
    ).toBe(true);
  });

  test("each read verdict gets its own sentence", () => {
    const at = (access: ProbeResult["access"]): string =>
      describeAccess({ root: "documents", path: "/d", access, recorded: false, note: null });
    expect(at({ kind: "ok", entries: 3 })).toContain("can read");
    expect(at({ kind: "denied", errno: 1 })).toContain("macOS is refusing it");
    expect(at({ kind: "notFound" })).toContain("does not exist");
    expect(at({ kind: "notADirectory" })).toContain("not a folder");
    expect(at({ kind: "error", detail: "errno-5" })).toContain("errno-5");
  });
});

/* ── T20: the verification loop ───────────────────────────────────────────────────────────────── */

describe("verify-flow", () => {
  const envelope = (
    extra: Partial<{
      kickstarted: boolean;
      outcome: string;
      skipReason: string | null;
      detail: string | null;
      iterations: number;
    }> = {},
  ) => ({
    kickstarted: true,
    outcome: "delivered",
    skipReason: null,
    detail: null,
    iterations: 1,
    ...extra,
  });

  test("a payload that is not a VerifyResult is not read as one", () => {
    expect(verifyEnvelope(null)).toBeNull();
    expect(verifyEnvelope({ outcome: "delivered" })).toBeNull();
    expect(verifyEnvelope({ kickstarted: true })).toBeNull();
    expect(verifyEnvelope(envelope())?.outcome).toBe("delivered");
  });

  test("a delivery ends the loop and falls through to the next-tick watch", () => {
    const stage = afterVerify(outcome({ payload: envelope() }), 1);
    expect(stage.stage).toBe("watching");
    expect(stage.stage === "watching" && stage.message).toContain("Confirmed");
    // ⚠ NO SECOND KICK. Plan R1 (final-check M3): a fresh install's first iteration may deliver a
    // THIN briefing, and `doctor`'s "repos need access" carries the thinness — retrying would
    // generate a second briefing for no new fact.
    expect(stage.stage).not.toBe("retrying");
  });

  test("a skip is confirmation that the trigger works, and loops to a bounded stop", () => {
    const skip = outcome({
      outcome: { kind: "delivered" },
      payload: envelope({ outcome: "skipped", skipReason: "offline", detail: "no network" }),
    });
    const first = afterVerify(skip, 1);
    expect(first.stage).toBe("retrying");
    expect(first.stage === "retrying" && first.attempt).toBe(2);
    expect(first.stage === "retrying" && first.message).toContain("offline");

    const last = afterVerify(skip, MAX_VERIFY_ATTEMPTS);
    expect(last.stage).toBe("stopped");
    expect(last.stage === "stopped" && last.message).toContain("the trigger works");
  });

  test("already-delivered-before-kick is NEVER rendered as a successful verification", () => {
    const stage = afterVerify(
      outcome({ payload: envelope({ outcome: "already-delivered-before-kick" }) }),
      1,
    );
    expect(stage.stage).toBe("stopped");
    const message = stage.stage === "stopped" ? stage.message : "";
    expect(message).toContain("Not confirmed");
    expect(message).not.toContain("Confirmed:");
    // And it is not retried: the day marker makes every further kick decline the same way.
    expect(stage.stage).not.toBe("retrying");
  });

  test("no evidence retries and then stops honestly", () => {
    const none = outcome({
      outcome: { kind: "failed", reason: null },
      exitCode: 1,
      payload: envelope({ outcome: "no-evidence" }),
    });
    expect(afterVerify(none, 1).stage).toBe("retrying");
    const stopped = afterVerify(none, MAX_VERIFY_ATTEMPTS);
    expect(stopped.stage).toBe("stopped");
    expect(stopped.stage === "stopped" && stopped.message).toContain("Not confirmed");
  });

  test("a refused kick and a missing envelope are both reported as refusals", () => {
    const refused = afterVerify(
      outcome({
        outcome: { kind: "failed", reason: "exit-3" },
        exitCode: 3,
        payload: envelope({ kickstarted: false }),
        stderr: "launchctl: could not kickstart",
      }),
      1,
    );
    expect(refused.stage).toBe("refused");
    expect(refused.stage === "refused" && refused.message).toContain("launchctl");

    const noEnvelope = afterVerify(
      outcome({ outcome: { kind: "failed", reason: "malformed-json" }, stderr: "boom" }),
      1,
    );
    expect(noEnvelope.stage).toBe("refused");
    expect(noEnvelope.stage === "refused" && noEnvelope.message).toBe("boom");
  });

  test("an outcome this version does not know is NOT a pass", () => {
    const stage = afterVerify(outcome({ payload: envelope({ outcome: "something-new" }) }), 1);
    expect(stage.stage).toBe("stopped");
    expect(stage.stage === "stopped" && stage.message).toContain("Not confirmed");
  });

  test("only a NEW skip record, or a delivery, counts as evidence", () => {
    expect(isNewEvidence({ skipIso: null, delivered: false }, null)).toBe(false);
    expect(isNewEvidence({ skipIso: "A", delivered: false }, "A")).toBe(false);
    expect(isNewEvidence({ skipIso: "B", delivered: false }, "A")).toBe(true);
    expect(isNewEvidence({ skipIso: "A", delivered: true }, "A")).toBe(true);
  });

  test("settled skip reasons end the loop with benign copy, never a retry", () => {
    // The engine's own settled set (`src/schedule/install.ts`): both PROVE the trigger reached
    // the engine, and neither is improved by another live kick. On a fresh install `already-ran`
    // is the INSTALL'S OWN first run, so it must not read as trouble.
    const already = afterVerify(
      outcome({ payload: envelope({ outcome: "skipped", skipReason: "already-ran" }) }),
      1,
    );
    expect(already.stage).toBe("watching");
    expect(already.stage === "watching" && already.message).toContain("Confirmed");
    expect(already.stage === "watching" && already.message).toContain("install's own first run");

    const floor = afterVerify(
      outcome({ payload: envelope({ outcome: "skipped", skipReason: "below-floor" }) }),
      1,
    );
    expect(floor.stage).toBe("watching");
    expect(floor.stage === "watching" && floor.message).toContain("Confirmed");

    // The additive rule cuts the other way for retries: a reason OUTSIDE the settled set —
    // including one this version does not know — may clear, so it keeps the bounded retry.
    const unknown = afterVerify(
      outcome({ payload: envelope({ outcome: "skipped", skipReason: "something-new" }) }),
      1,
    );
    expect(unknown.stage).toBe("retrying");
    expect(
      afterVerify(
        outcome({ payload: envelope({ outcome: "skipped", skipReason: "something-new" }) }),
        MAX_VERIFY_ATTEMPTS,
      ).stage,
    ).toBe("stopped");
  });

  /* ── the loop state machine (round 1 — the HIGH lived here) ────────────────────────────────── */

  const skipped = (reason: string): EngineOutcome =>
    outcome({ payload: envelope({ outcome: "skipped", skipReason: reason }) });

  test("a skip record produced by the loop's own kick is absorbed, in BOTH windows", () => {
    // Window 1: the watcher's push lands while the kick's IPC is still in flight.
    let s = beginKick({ skipIso: "A", delivered: false }, 1);
    let r = onEvidence(s, { skipIso: "B", delivered: false });
    expect(r.kick).toBeNull();
    expect(r.state.seenSkipIso).toBe("B");
    s = afterKick(r.state, skipped("offline"), 1, { skipIso: "B", delivered: false });
    expect(s.stage.stage).toBe("retrying");
    expect(s.ownSkipPending).toBe(false);
    // The record already accounted for does not re-arm…
    expect(onEvidence(s, { skipIso: "B", delivered: false }).kick).toBeNull();
    // …and the NEXT tick's record does.
    expect(onEvidence(s, { skipIso: "C", delivered: false }).kick).toBe(2);

    // Window 2: the push arrives only AFTER the loop has entered `retrying` (the ~250 ms debounce
    // usually beats the IPC return, but that ordering is NOT guaranteed). The engine's `skipped`
    // answer proves a record the app has not seen yet, so the FIRST new iso is the kick's own
    // output — absorbed — and only the one after it arms the next kick.
    s = beginKick({ skipIso: "A", delivered: false }, 1);
    s = afterKick(s, skipped("offline"), 1, { skipIso: "A", delivered: false });
    expect(s.stage.stage).toBe("retrying");
    expect(s.ownSkipPending).toBe(true);
    r = onEvidence(s, { skipIso: "B", delivered: false });
    expect(r.kick).toBeNull();
    expect(r.state.seenSkipIso).toBe("B");
    r = onEvidence(r.state, { skipIso: "C", delivered: false });
    expect(r.kick).toBe(2);
  });

  test("onEvidence agrees with isNewEvidence wherever the refinement is inert", () => {
    // Round 2: `isNewEvidence` is production-dead — round 1 moved the loop into `onEvidence`,
    // which REFINES the predicate (own-kick absorption, the predates-the-kick delivery rule)
    // instead of calling it — and its doc keeps it as "the table the refinement is judged
    // against". This is the judging, so the two cannot drift silently. In a PLAIN retrying state
    // (no own skip pending, no delivery on the books at kick) the refinements are inert, and
    // `onEvidence` must ACT — arm a kick, or confirm a delivery — exactly when `isNewEvidence`
    // says the push is new evidence, over the same evidence/baseline table.
    let s = beginKick({ skipIso: "A", delivered: false }, 1);
    s = afterKick(s, skipped("offline"), 1, { skipIso: "B", delivered: false });
    expect(s.stage.stage).toBe("retrying");
    expect(s.ownSkipPending).toBe(false);
    expect(s.deliveredAtKick).toBe(false);
    const table: VerifyEvidence[] = [
      { skipIso: null, delivered: false }, // nothing on the books — not evidence
      { skipIso: "B", delivered: false }, // already accounted for — not evidence
      { skipIso: "C", delivered: false }, // a new record — evidence (arms the kick)
      { skipIso: "B", delivered: true }, // a delivery — evidence (confirms, never kicks)
    ];
    for (const evidence of table) {
      const r = onEvidence(s, evidence);
      const acted = r.kick !== null || r.state !== s;
      expect(acted).toBe(isNewEvidence(evidence, s.seenSkipIso));
    }
  });

  test("a delivery during the loop ends it in watching — never a kick", () => {
    // While retrying…
    let s = beginKick({ skipIso: "A", delivered: false }, 1);
    s = afterKick(s, skipped("offline"), 1, { skipIso: "B", delivered: false });
    let r = onEvidence(s, { skipIso: "B", delivered: true });
    expect(r.kick).toBeNull();
    expect(r.state.stage.stage).toBe("watching");
    // …and while the kick is still in flight: the loop settles, and the LATE IPC answer (and a
    // late `busy` rejection) is dropped rather than un-confirming a delivery.
    s = beginKick({ skipIso: "A", delivered: false }, 1);
    r = onEvidence(s, { skipIso: "A", delivered: true });
    expect(r.kick).toBeNull();
    expect(r.state.stage.stage).toBe("watching");
    expect(afterKick(r.state, skipped("offline"), 1, { skipIso: "A", delivered: true }).stage.stage).toBe(
      "watching",
    );
    expect(afterKickRefusal(r.state, "busy").stage.stage).toBe("watching");
  });

  test("a delivery that PREDATES the kick is not read as the loop's confirmation", () => {
    // A manual check while today's briefing is already on the books: §3 — already-delivered is
    // never a success, and the kick's own envelope (`already-delivered-before-kick`) is the honest
    // answer, so the push must not preempt it.
    const s = beginKick({ skipIso: "A", delivered: true }, 1);
    const r = onEvidence(s, { skipIso: "A", delivered: true });
    expect(r.kick).toBeNull();
    expect(r.state.stage.stage).toBe("verifying");
  });

  test("arming the loop with a delivery already on the books confirms WITHOUT a kick", () => {
    // Plan R1 (final-check M3), directly: the install's own kickstart delivered, so the panel
    // watches — it does not issue a live kick whose only possible answers restate what is known.
    const armed = armLoop({ skipIso: "A", delivered: true });
    expect(armed.kick).toBeNull();
    expect(armed.state.stage.stage).toBe("watching");
    expect(armed.state.stage.stage === "watching" && armed.state.stage.message).toContain(
      "Confirmed",
    );
    const kicked = armLoop({ skipIso: "A", delivered: false });
    expect(kicked.kick).toBe(1);
    expect(kicked.state.stage.stage).toBe("verifying");
  });

  test("the evidence fold is a fixed point, so a reactive caller cannot loop on it", () => {
    // `onEvidence` returns the SAME object when nothing changed — the component's `$effect`
    // compares by reference. After any change it applies, folding the same evidence again must
    // change nothing and kick nothing.
    const idle = { skipIso: null, delivered: false };
    let s = beginKick(idle, 1);
    expect(onEvidence(s, idle).state).toBe(s);
    const pushed = { skipIso: "B", delivered: false };
    let r = onEvidence(s, pushed);
    expect(onEvidence(r.state, pushed).state).toBe(r.state);
    const delivered = { skipIso: "B", delivered: true };
    r = onEvidence(s, delivered);
    expect(onEvidence(r.state, delivered).state).toBe(r.state);
    expect(onEvidence(r.state, delivered).kick).toBeNull();
  });

  test("the control says what it will do before it does it", () => {
    const body = html(ScheduleVerify, { evidence: { skipIso: null, delivered: false } });
    expect(buttons(body)).toEqual(["Check the background scheduler now"]);
    expect(body).toContain("It can generate today's briefing.");
  });
});

/* ── T20: the removal ─────────────────────────────────────────────────────────────────────────── */

describe("uninstall-flow", () => {
  test("the confirmation names the file and the consequence", () => {
    const c = uninstallConfirmation(scheduleState());
    expect(c.unitPath).toBe("/Users/x/Library/LaunchAgents/local.daily-briefing.plist");
    expect(c.body).toContain("/Users/x/Library/LaunchAgents/local.daily-briefing.plist");
    expect(c.body).toContain("Nothing will generate a briefing after that");
    expect(c.body).toContain("archive are untouched");
    expect(c.foreign).toBe(false);
  });

  test("with no unit path it says so rather than naming one this app computed", () => {
    const c = uninstallConfirmation(scheduleState({ unitPath: null }));
    expect(c.unitPath).toBeNull();
    expect(c.body).toContain("did not report a file path");
  });

  test("a CLI-owned schedule warns that removing it needs a second confirmation", () => {
    const c = uninstallConfirmation(scheduleState({ owner: "cli", invoker: "cli" }));
    expect(c.foreign).toBe(true);
    expect(c.body).toContain("installed from the command line");
  });

  test("exit 1 is `there was nothing to remove`, keyed on the exit code", () => {
    // ⚠ `reason` IS NULL HERE — gui-seam §3: the classifier invents no reason string for exit 1, so
    // a panel keying on `reason` would show an empty error for an ordinary outcome.
    const stage = afterUninstall(
      outcome({
        operation: "schedule-uninstall",
        outcome: { kind: "failed", reason: null },
        exitCode: 1,
      }),
      false,
      "app",
    );
    expect(stage.stage).toBe("done");
    expect(stage.message).toContain("nothing to remove");
  });

  test("a foreign owner offers take-over once, and a refused take-over does not loop", () => {
    const refusal = outcome({
      operation: "schedule-uninstall",
      outcome: { kind: "configError" },
      exitCode: 2,
      stderr: "schedule: refusing — this schedule is owned by cli",
    });
    expect(afterUninstall(refusal, false, "cli").stage).toBe("foreign-owner");
    // Already took over and still refused: a failure, never a second dialog.
    expect(afterUninstall(refusal, true, "cli").stage).toBe("failed");
    // Owned by this app: exit 2 is some other refusal, and take-over would answer a question
    // nobody asked.
    expect(afterUninstall(refusal, false, "app").stage).toBe("failed");
    expect(afterUninstall(refusal, false, null).stage).toBe("failed");
  });

  test("the first control is the confirmation, not the removal", () => {
    const body = html(ScheduleUninstall, { scheduleState: scheduleState() });
    expect(buttons(body)).toEqual(["Remove background scheduler…"]);
    // The destructive label and the consequence are behind it, not on the screen by default.
    expect(body).not.toContain("Nothing will generate a briefing after that");
  });
});
